"""Event + AISignal MAC fields

Revision ID: bff3b55b9481
Revises: 6c70531b8030
Create Date: 2025-11-25 23:35:08.178474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff3b55b9481'
down_revision = '6c70531b8030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mac', sa.String(length=17), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_signal_mac'), ['mac'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mac', sa.String(length=17), nullable=True))
        batch_op.add_column(sa.Column('detail', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_event_device_id'))
        batch_op.drop_index(batch_op.f('ix_event_organization_id'))
        batch_op.drop_index(batch_op.f('ix_event_ts'))
        batch_op.create_index(batch_op.f('ix_event_mac'), ['mac'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_mac'))
        batch_op.create_index(batch_op.f('ix_event_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_device_id'), ['device_id'], unique=False)
        batch_op.drop_column('detail')
        batch_op.drop_column('mac')
        batch_op.drop_column('action')
        batch_op.drop_column('category')

    with op.batch_alter_table('ai_signal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_signal_mac'))
        batch_op.drop_column('mac')

    # ### end Alembic commands ###
